import { Link } from "wouter";
import { useState, useEffect, useRef } from "react";

const COMPARISON_ROWS = [
  { project: "Worldcoin", biometricRooted: true, noStorage: false, noIdentity: false, existingHW: false, devSimple: false, gap: "Requires proprietary Orb hardware; single company controls biometric data" },
  { project: "BrightID", biometricRooted: false, noStorage: true, noIdentity: true, existingHW: true, devSimple: false, gap: "Vulnerable to sybil collusion; not biometric-rooted" },
  { project: "Proof of Humanity", biometricRooted: false, noStorage: false, noIdentity: false, existingHW: true, devSimple: false, gap: "High friction; not scalable; not private" },
  { project: "Civic", biometricRooted: false, noStorage: false, noIdentity: false, existingHW: true, devSimple: false, gap: "Requires government ID; full identity exposure" },
  { project: "Gitcoin Passport", biometricRooted: false, noStorage: true, noIdentity: true, existingHW: true, devSimple: true, gap: "No biometric root; determined bot can acquire all credentials" },
  { project: "POP Protocol", biometricRooted: true, noStorage: true, noIdentity: true, existingHW: true, devSimple: true, gap: null },
];

const USE_CASES = [
  { tier: "01", label: "Platform Integrity", desc: "Social networks, forums, review platforms. One verified human per account. Bots can't register. Reviews can't be synthesized at scale." },
  { tier: "02", label: "Democratic Processes", desc: "Online voting, community governance, polls. One vote per human is mathematically enforced — without the surveillance of government ID." },
  { tier: "03", label: "Financial Applications", desc: "Prevent sybil attacks in DeFi, ensure one-per-human token distribution, serve as a KYC alternative where formal ID is unavailable." },
  { tier: "04", label: "AI Interaction Transparency", desc: "Cryptographic proof that a message, post, or piece of content was authored by a verified human — not generated by an AI agent." },
  { tier: "05", label: "Human-Only Spaces", desc: "Therapy platforms, peer support, professional networks that need to enforce human-only participation without platform-level surveillance." },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Biometric Commitment",
    desc: "Your device captures a biometric signal locally. A cryptographic commitment C = Hash(biometric, salt) is derived. The commitment — not the biometric — is published on-chain.",
    detail: "Your fingerprint never leaves your device. Only an irreversible mathematical hash is stored.",
  },
  {
    step: "02",
    title: "Zero-Knowledge Proof",
    desc: "When you need to verify to an application, your device generates a zkSNARK proof: 'I know a biometric that corresponds to a registered commitment, and this nullifier has not been used before.'",
    detail: "The application verifies the proof cryptographically. It learns you are human — and nothing else.",
  },
  {
    step: "03",
    title: "Human Badge Issued",
    desc: "The application receives a cryptographic badge token. It stores this token alongside your account — a permanent, unforgeable proof that a real human registered here.",
    detail: "One nullifier per application context. You cannot register twice. You cannot impersonate. You cannot be identified.",
  },
];

const HW_TIERS = [
  { tier: "Tier 1", name: "Phone Camera", coverage: "Every smartphone on earth", detail: "Face geometry extracted from a standard camera. Lowest security baseline — suitable for most consumer applications.", security: 40 },
  { tier: "Tier 2", name: "Secure Enclave", coverage: "~3 billion devices", detail: "Integrates with existing secure enclave APIs (Face ID, Android fingerprint). Biometric never leaves the chip. Production-grade security.", security: 78 },
  { tier: "Tier 3", name: "Certified Hardware", coverage: "High-stakes only", detail: "Open hardware spec that multiple manufacturers can produce. For voting, large financial transactions. No single-vendor lock-in.", security: 97 },
];

function Check({ filled }: { filled: boolean }) {
  if (filled) {
    return (
      <span className="inline-block w-4 h-4 bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold" data-testid="check-yes">
        <svg width="10" height="8" viewBox="0 0 10 8" fill="none"><path d="M1 4L3.5 6.5L9 1" stroke="currentColor" strokeWidth="2" strokeLinecap="square"/></svg>
      </span>
    );
  }
  return (
    <span className="inline-block w-4 h-4 border border-border text-muted-foreground flex items-center justify-center text-xs" data-testid="check-no">
      <svg width="8" height="8" viewBox="0 0 8 8" fill="none"><path d="M1 1L7 7M7 1L1 7" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square"/></svg>
    </span>
  );
}

function AnimatedNumber({ value }: { value: number }) {
  const [display, setDisplay] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);
  useEffect(() => {
    let start = 0;
    const duration = 1800;
    const startTime = performance.now();
    function tick(now: number) {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setDisplay(Math.round(eased * value));
      if (progress < 1) requestAnimationFrame(tick);
    }
    requestAnimationFrame(tick);
  }, [value]);
  return <span ref={ref}>{display.toLocaleString()}</span>;
}

export function Home() {
  const [heroVisible, setHeroVisible] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setHeroVisible(true), 60);
    return () => clearTimeout(t);
  }, []);

  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="relative min-h-[90vh] flex flex-col items-center justify-center px-4 overflow-hidden border-b border-border" data-testid="section-hero">
        <div className="absolute inset-0 grid-bg pointer-events-none" />
        <div className={`absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] rounded-full opacity-10 blur-[120px] bg-primary pointer-events-none transition-opacity duration-1000 ${heroVisible ? 'opacity-10' : 'opacity-0'}`} />
        <div className={`relative z-10 max-w-4xl w-full mx-auto text-center transition-all duration-700 ${heroVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}>
          <div className="inline-flex items-center gap-2 border border-primary/30 bg-primary/5 px-3 py-1 text-xs font-mono text-primary mb-8 tracking-widest uppercase">
            <span className="w-1.5 h-1.5 bg-primary rounded-full animate-pulse" />
            Cryptographic Human Verification
          </div>
          <h1 className="text-5xl md:text-7xl lg:text-8xl font-medium tracking-tight leading-[0.95] mb-6">
            Proof of<br />
            <span className="text-primary">Personhood</span><br />
            Protocol
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed font-mono">
            Any person. Any platform. Cryptographically verified as unique and human — without revealing who they are.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/demo" data-testid="button-hero-demo" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-8 py-3 font-medium text-sm hover:bg-primary/90 transition-colors">
              Run Live Demo
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6H10M7 3L10 6L7 9" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square"/></svg>
            </Link>
            <Link href="/developers" data-testid="button-hero-developers" className="inline-flex items-center gap-2 border border-border px-8 py-3 font-medium text-sm hover:border-primary/50 hover:text-primary transition-colors">
              Developer Docs
            </Link>
          </div>
        </div>
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-1 text-xs text-muted-foreground font-mono">
          <span>SCROLL</span>
          <div className="w-px h-8 bg-border" />
        </div>
      </section>

      {/* Core Problem */}
      <section className="py-24 px-4 border-b border-border" data-testid="section-problem">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
            <div>
              <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">The Problem</p>
              <h2 className="text-4xl md:text-5xl font-medium tracking-tight mb-6 leading-tight">
                The internet was built without a native identity layer.
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                For 30 years, fake accounts were annoying. Bots were a nuisance. Spam was a cost of doing business. This was tolerable.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                Today, a single developer can generate 10 million convincing AI personas in an afternoon — each with a unique name, writing style, photo, browsing history, and social graph. The internet's assumption of human presence has permanently collapsed.
              </p>
            </div>
            <div className="flex flex-col gap-4">
              {[
                { q: "What does it mean to vote online when you cannot verify the voters are human?" },
                { q: "What does it mean to review a product when reviews can be infinitely synthesized?" },
                { q: "What does it mean to have a conversation when the other participant might be a simulation?" },
              ].map((item, i) => (
                <div key={i} className="border border-border bg-card p-6" data-testid={`problem-question-${i}`}>
                  <p className="font-mono text-sm leading-relaxed text-foreground/80">{item.q}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-4 border-b border-border bg-card" data-testid="section-how-it-works">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">The Architecture</p>
          <h2 className="text-4xl font-medium tracking-tight mb-16">How it works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-0 border border-border">
            {HOW_IT_WORKS.map((step, i) => (
              <div key={i} className={`p-8 ${i < 2 ? 'border-b md:border-b-0 md:border-r border-border' : ''}`} data-testid={`how-step-${i}`}>
                <div className="font-mono text-5xl font-medium text-primary/20 mb-6">{step.step}</div>
                <h3 className="text-xl font-medium mb-3">{step.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed mb-4">{step.desc}</p>
                <p className="font-mono text-xs text-primary/70 leading-relaxed">{step.detail}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 border border-border bg-background p-6 font-mono text-xs text-muted-foreground">
            <span className="text-primary">C</span> = Hash(biometric, salt) &nbsp;|&nbsp; <span className="text-primary">N</span> = Hash(biometric, app_context) &nbsp;|&nbsp; <span className="text-primary">ZK</span> = prove(C ∈ registry, N unused, liveness=true) &nbsp;|&nbsp; <span className="text-primary">Badge</span> = verify(ZK) → token
          </div>
        </div>
      </section>

      {/* Hardware Tiers */}
      <section className="py-24 px-4 border-b border-border" data-testid="section-hardware">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Hardware Spectrum</p>
          <h2 className="text-4xl font-medium tracking-tight mb-4">Accessible to every human on earth</h2>
          <p className="text-muted-foreground mb-16 max-w-2xl">The weakest point of existing systems is hardware. The protocol is designed to support a spectrum from any smartphone to high-security specialized hardware.</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-0 border border-border">
            {HW_TIERS.map((tier, i) => (
              <div key={i} className={`p-8 ${i < 2 ? 'border-b md:border-b-0 md:border-r border-border' : ''}`} data-testid={`hw-tier-${i}`}>
                <div className="flex items-center justify-between mb-6">
                  <span className="font-mono text-xs text-primary tracking-widest">{tier.tier}</span>
                  <span className="font-mono text-xs text-muted-foreground">{tier.security}% security</span>
                </div>
                <div className="h-1 bg-border mb-6">
                  <div className="h-1 bg-primary transition-all duration-1000" style={{ width: `${tier.security}%` }} />
                </div>
                <h3 className="text-lg font-medium mb-1">{tier.name}</h3>
                <p className="text-xs font-mono text-primary/70 mb-3">{tier.coverage}</p>
                <p className="text-muted-foreground text-sm leading-relaxed">{tier.detail}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Comparison Table */}
      <section className="py-24 px-4 border-b border-border bg-card" data-testid="section-comparison">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Competitive Landscape</p>
          <h2 className="text-4xl font-medium tracking-tight mb-4">What the others got wrong</h2>
          <p className="text-muted-foreground mb-12 max-w-2xl">Several serious attempts have been made. None have solved all five requirements simultaneously.</p>
          <div className="border border-border overflow-x-auto">
            <table className="w-full text-sm" data-testid="comparison-table">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left p-4 font-mono text-xs text-muted-foreground font-normal">Project</th>
                  <th className="text-center p-4 font-mono text-xs text-muted-foreground font-normal">Biometric-rooted</th>
                  <th className="text-center p-4 font-mono text-xs text-muted-foreground font-normal">No storage</th>
                  <th className="text-center p-4 font-mono text-xs text-muted-foreground font-normal">No identity</th>
                  <th className="text-center p-4 font-mono text-xs text-muted-foreground font-normal">Existing HW</th>
                  <th className="text-center p-4 font-mono text-xs text-muted-foreground font-normal">Dev-simple</th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON_ROWS.map((row, i) => (
                  <tr key={i} className={`border-b border-border last:border-b-0 ${!row.gap ? 'bg-primary/5' : ''}`} data-testid={`comparison-row-${i}`}>
                    <td className="p-4 font-medium font-mono text-xs">
                      {!row.gap ? <span className="text-primary">{row.project} ✓</span> : row.project}
                    </td>
                    <td className="p-4 text-center"><Check filled={row.biometricRooted} /></td>
                    <td className="p-4 text-center"><Check filled={row.noStorage} /></td>
                    <td className="p-4 text-center"><Check filled={row.noIdentity} /></td>
                    <td className="p-4 text-center"><Check filled={row.existingHW} /></td>
                    <td className="p-4 text-center"><Check filled={row.devSimple} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-24 px-4 border-b border-border" data-testid="section-use-cases">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Applications</p>
          <h2 className="text-4xl font-medium tracking-tight mb-16">Use cases</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-0 border border-border">
            {USE_CASES.map((uc, i) => (
              <div key={i} className={`p-8 border-b border-border ${i % 3 !== 2 ? 'lg:border-r' : ''} ${i % 2 !== 1 ? 'md:border-r lg:border-r-0' : 'md:border-r-0'} ${i >= 3 ? 'md:border-b-0' : ''} ${i === 4 ? 'lg:border-r' : ''}`} data-testid={`use-case-${i}`}>
                <div className="font-mono text-xs text-primary/50 mb-4">{uc.tier}</div>
                <h3 className="font-medium mb-3">{uc.label}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{uc.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Business Model */}
      <section className="py-24 px-4 border-b border-border bg-card" data-testid="section-business">
        <div className="max-w-6xl mx-auto">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Business Model</p>
          <h2 className="text-4xl font-medium tracking-tight mb-4">Public good. Commercial infrastructure.</h2>
          <p className="text-muted-foreground mb-16 max-w-2xl">Proof of personhood can only work as a standard if nobody controls it. The protocol is open-source and governed by a non-profit foundation. The commercial company provides the infrastructure layer.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-0 border border-border">
            <div className="p-8 border-b md:border-b-0 md:border-r border-border">
              <p className="font-mono text-xs text-muted-foreground mb-4">FOUNDATION LAYER</p>
              <h3 className="text-xl font-medium mb-4">Open-source protocol</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Smart contracts, ZK circuits, cryptographic spec</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Protocol fees: 1–2% of paid verifications to foundation treasury</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Grants from governments, NGOs, crypto foundations</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Governed by decentralized process</li>
              </ul>
            </div>
            <div className="p-8">
              <p className="font-mono text-xs text-muted-foreground mb-4">COMMERCIAL LAYER</p>
              <h3 className="text-xl font-medium mb-4">Infrastructure API</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Managed verification API: $0.001–$0.01 per proof verification</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Enterprise compliance suite: $50K–$500K/year</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Hardware certification program for device manufacturers</li>
                <li className="flex gap-2"><span className="text-primary font-mono">—</span> Human Badge API: $1K–$50K/month by volume</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Stats teaser */}
      <section className="py-20 px-4 border-b border-border" data-testid="section-stats-teaser">
        <div className="max-w-6xl mx-auto text-center">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Live Network</p>
          <h2 className="text-3xl font-medium tracking-tight mb-10">Protocol is active</h2>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-8">
            <Link href="/stats" data-testid="button-view-stats" className="inline-flex items-center gap-2 border border-border px-6 py-3 font-mono text-sm hover:border-primary/50 hover:text-primary transition-colors">
              View Live Stats
            </Link>
            <Link href="/demo" data-testid="button-run-demo" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 font-mono text-sm hover:bg-primary/90 transition-colors">
              Run the Demo
            </Link>
          </div>
        </div>
      </section>

      {/* End state quote */}
      <section className="py-32 px-4" data-testid="section-vision">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-2xl md:text-3xl leading-relaxed text-muted-foreground font-mono">
            "The Proof of Personhood Protocol becomes what HTTPS became — an invisible layer that every application uses, that nobody notices, that makes everything else safer and more trustworthy."
          </p>
          <div className="mt-12 flex items-center justify-center gap-2">
            <div className="w-1 h-1 bg-primary" />
            <div className="w-1 h-1 bg-primary/50" />
            <div className="w-1 h-1 bg-primary/20" />
          </div>
        </div>
      </section>
    </div>
  );
}
